apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clear-sessions
  namespace: dev-investmann-main-distracted-keldysh
  labels:
    app.kubernetes.io/name: django
spec:
  schedule: "@monthly"
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 100
      activeDeadlineSeconds: 100
      template:
        metadata:
          labels:
            app.kubernetes.io/name: django
        spec:
          restartPolicy: Never
          containers:
          - name: django
            image: cr.yandex/crppvo9bpgsbl1m4dccq/django:<COMMIT_HASH>
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: django
            env:
              - name: DJ__SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: django
                    key: secret_key
                    optional: false
              - name: ROLLBAR__BACKEND_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: rollbar
                    key: backend_token
                    optional: false
              - name: POSTGRES_DSN
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: dsn
                    optional: false
              - name: TG__WEBHOOK_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: tg-bot
                    key: webhook_token
                    optional: false
              - name: TG__BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: tg-bot
                    key: token
                    optional: false
              - name: S3_DSN
                valueFrom:
                  secretKeyRef:
                    name: bucket
                    key: dsn
                    optional: false
            volumeMounts:
              - mountPath: "/root/.postgresql/"
                name: psql-cert
                readOnly: true
            command:
              - python
              - manage.py
              - clearsessions
          volumes:
            - name: psql-cert
              secret:
                secretName: psql-root-crt
