# Generated by Django 4.2.1 on 2023-12-11 16:33

from django.db import migrations
from django_tg_bot_framework import locator_field


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='state_machine_locator',
            field=locator_field.LocatorField(blank=True, help_text='Локатор состояния, в котором сейчас находится чат с пользователем. Заполняется автоматически. Используется стейт-машиной.<br>Пример значения: <code>{"state_class_locator": "/start-menu/"}</code>.<br>В поле хранится объект JSON в формате локатора из библиотеки <a href="https://pypi.org/project/yostate/">yostate</a>: атрибут <code>state_class_locator</code> указывает локатор класса состояния и похож на часть адреса URL, атрибут <code>params</code> задаёт параметры состояния.', null=True, verbose_name='Cостояние'),
        ),
    ]
