# Generated by Django 4.2.1 on 2024-02-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_remove_imagemessage_series_remove_textmessage_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_update_language_code',
            field=models.CharField(blank=True, db_index=True, help_text='Языковой код установленный у пользователя в телеграмме.', max_length=8, verbose_name='Языковой код юзера Tg'),
        ),
    ]
