# Generated by Django 4.2.1 on 2024-02-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_conversation_last_update_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='force_language',
            field=models.CharField(blank=True, db_index=True, help_text='Языковой код, выбранный пользователем вручную', max_length=8, verbose_name='Выбранный пользователем язык'),
        ),
    ]
