# Generated by Django 4.2.1 on 2024-01-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgMessageSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(db_index=True, help_text='Пространство имён помогает избежать коллизий из-за похожих имен серий.', max_length=200, verbose_name='Пространство имен')),
                ('name', models.CharField(db_index=True, help_text='Имя серии сообщений внутри пространства имён.', max_length=100, verbose_name='Название')),
                ('language_code', models.CharField(db_index=True, help_text='Языковой код серии сообщений', max_length=6, verbose_name='Язык')),
                ('draft', models.BooleanField(db_index=True, default=False, help_text='Черновик не используется в работе бота', verbose_name='Черновик')),
                ('disable_notification', models.BooleanField(default=False, help_text='Пользователи получат уведомление без звука.', verbose_name='Отправить тихо')),
            ],
            options={
                'verbose_name': 'Сообщение бота',
                'verbose_name_plural': 'Сообщения бота',
                'unique_together': {('namespace', 'name', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='TgTextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('protect_content', models.BooleanField(default=False, verbose_name='Защитить от сохранения и пересылки')),
                ('disable_web_page_preview', models.BooleanField(default=False, verbose_name='Отключить предпросмотр вэб-страниц')),
                ('parse_mode', models.CharField(blank=True, choices=[('', 'Не используется'), ('HTML', 'HTML'), ('Markdown', 'Markdown')], default='', max_length=16, verbose_name='Форматирование')),
                ('message_order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер в серии')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_messages', to='editable_messages.tgmessageseries')),
            ],
            options={
                'verbose_name': 'Текстовое сообщение',
                'verbose_name_plural': 'Текстовые сообщения',
            },
        ),
        migrations.CreateModel(
            name='TgImageMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('protect_content', models.BooleanField(default=False, verbose_name='Защитить от сохранения и пересылки')),
                ('has_spoiler', models.BooleanField(default=False, verbose_name='Спойлер')),
                ('message_order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер в серии')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_messages', to='editable_messages.tgmessageseries')),
            ],
            options={
                'verbose_name': 'Сообщение с картинкой',
                'verbose_name_plural': 'Сообщения с картинками',
            },
        ),
        migrations.CreateModel(
            name='TgDocumentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Документ')),
                ('protect_content', models.BooleanField(default=False, verbose_name='Защитить от сохранения и пересылки')),
                ('disable_content_type_detection', models.BooleanField(default=False, help_text='Отключение автоматического определения типа содержимого файла на стороне сервера.', verbose_name='Не проверять тип файла')),
                ('message_order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер в серии')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_messages', to='editable_messages.tgmessageseries')),
            ],
            options={
                'verbose_name': 'Сообщение с документом',
                'verbose_name_plural': 'Сообщения с документами',
            },
        ),
    ]
