# Generated by Django 4.2.1 on 2024-01-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessageseries',
            name='language_code',
            field=models.CharField(choices=[('ru_ru', 'ru_ru')], db_index=True, default='ru_ru', help_text='Языковой код серии сообщений', verbose_name='Язык'),
        ),
    ]
