# Generated by Django 4.2.1 on 2024-02-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editable_messages', '0002_alter_tgmessageseries_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgdocumentmessage',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editable_messages.tgmessageseries'),
        ),
        migrations.AlterField(
            model_name='tgimagemessage',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editable_messages.tgmessageseries'),
        ),
        migrations.AlterField(
            model_name='tgtextmessage',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editable_messages.tgmessageseries'),
        ),
    ]
