# Generated by Django 4.2.1 on 2024-02-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editable_messages', '0003_alter_tgdocumentmessage_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgInlineButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('callback_data', models.CharField(blank=True, default='', max_length=64, verbose_name='callback data')),
                ('url', models.URLField(blank=True, default='', help_text='url для перехода при нажатии', verbose_name='URL')),
                ('message_number', models.SmallIntegerField(help_text='Номер в сообщения в серии.ю к которому будут привязана кнопка', verbose_name='Номер сообщения')),
                ('row', models.SmallIntegerField(verbose_name='Ряд в клавиатуре')),
                ('position_in_row', models.SmallIntegerField(verbose_name='Место в ряду')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_buttons', to='editable_messages.tgmessageseries')),
            ],
        ),
    ]
