# Generated by Django 4.2.1 on 2024-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_messages', '0004_tginlinebutton'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tginlinebutton',
            options={'verbose_name': 'Ин-лайн кнопка', 'verbose_name_plural': 'Ин-лайн кнопки'},
        ),
        migrations.AlterField(
            model_name='tginlinebutton',
            name='message_number',
            field=models.SmallIntegerField(help_text='Номер сообщения в серии, к которому будет привязана кнопка', verbose_name='Номер сообщения'),
        ),
    ]
