# Generated by Django 4.2.1 on 2024-02-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_messages', '0005_alter_tginlinebutton_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessageseries',
            name='language_code',
            field=models.CharField(db_index=True, help_text='Языковой код серии сообщений', verbose_name='Язык'),
        ),
    ]
