# Generated by Django 4.2.1 on 2024-02-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_messages', '0006_alter_tgmessageseries_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessageseries',
            name='language_code',
            field=models.CharField(db_index=True, help_text='Языковой код серии сообщений', max_length=8, verbose_name='Язык'),
        ),
    ]
