# Generated by Django 4.2.1 on 2024-02-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_messages', '0008_alter_tgmessageseries_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgdocumentmessage',
            name='message_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер в серии'),
        ),
        migrations.AlterField(
            model_name='tgimagemessage',
            name='message_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер в серии'),
        ),
        migrations.AlterField(
            model_name='tginlinebutton',
            name='message_number',
            field=models.PositiveSmallIntegerField(help_text='Номер сообщения в серии, к которому будет привязана кнопка', verbose_name='Номер сообщения'),
        ),
        migrations.AlterField(
            model_name='tgtextmessage',
            name='message_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер в серии'),
        ),
    ]
