# Generated by Django 4.2.1 on 2024-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_messages', '0009_alter_tgdocumentmessage_message_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tginlinebutton',
            name='message_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Номер сообщения в серии, к которому будет привязана кнопка', null=True, verbose_name='Номер сообщения'),
        ),
    ]
