# Generated by Django 4.2.1 on 2024-03-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_messages', '0010_alter_tginlinebutton_message_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tginlinebutton',
            options={'verbose_name': 'Инлайн кнопка', 'verbose_name_plural': 'Инлайн кнопки'},
        ),
        migrations.AlterField(
            model_name='tgdocumentmessage',
            name='message_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='При отправке нескольких сообщений, они будут отправлены в порядке своих номеров', verbose_name='Номер в серии'),
        ),
        migrations.AlterField(
            model_name='tgdocumentmessage',
            name='protect_content',
            field=models.BooleanField(default=False, help_text='Запретить пересылать сообщение и сохранять его содержимое', verbose_name='Защищенное сообщение'),
        ),
        migrations.AlterField(
            model_name='tgimagemessage',
            name='message_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='При отправке нескольких сообщений, они будут отправлены в порядке своих номеров', verbose_name='Номер в серии'),
        ),
        migrations.AlterField(
            model_name='tgimagemessage',
            name='protect_content',
            field=models.BooleanField(default=False, help_text='Запретить пересылать сообщение и сохранять его содержимое', verbose_name='Защищенное сообщение'),
        ),
        migrations.AlterField(
            model_name='tginlinebutton',
            name='callback_data',
            field=models.CharField(blank=True, default='', help_text='Данные, отправляемые боту при нажатии кнопки. Не может быть заполнено одновременно с url', max_length=64, verbose_name='callback data'),
        ),
        migrations.AlterField(
            model_name='tginlinebutton',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Ссылка для перехода при нажатии. Не может быть заполнено одновременно с callback data', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tgmessageseries',
            name='language_code',
            field=models.CharField(db_index=True, help_text='Язык сообщения', max_length=8, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='tgmessageseries',
            name='name',
            field=models.CharField(db_index=True, help_text='Имя сообщения', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tgmessageseries',
            name='namespace',
            field=models.CharField(db_index=True, help_text='Адрес в схеме сообщений позволяет избежать коллизий из-за одинаковых имён', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='tgtextmessage',
            name='disable_web_page_preview',
            field=models.BooleanField(default=False, help_text='Предпросмотр ссылок - это отображение содержимого сайта в теле сообщения', verbose_name='Отключить предпросмотр ссылок'),
        ),
        migrations.AlterField(
            model_name='tgtextmessage',
            name='message_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='При отправке нескольких сообщений, они будут отправлены в порядке своих номеров', verbose_name='Номер в серии'),
        ),
        migrations.AlterField(
            model_name='tgtextmessage',
            name='protect_content',
            field=models.BooleanField(default=False, help_text='Запретить пересылать сообщение и сохранять его содержимое', verbose_name='Защищенное сообщение'),
        ),
    ]
