# Generated by Django 4.2.1 on 2023-11-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField(db_index=True, help_text='Id пользователя Telegram. Пример значения: <code>123456789</code>.<br>Чтобы узнать ID пользователя, перешлите сообщение пользователя боту <a href="https://t.me/userinfobot">@userinfobot</a>.', verbose_name='Id юзера в Tg')),
                ('funnel_slug', models.SlugField(help_text='Англоязычное название воронки, например "greeting_mailing". Разрешены те же символы, что бывают внутри slug.', verbose_name='воронка')),
                ('state_machine_locator', models.JSONField(blank=True, help_text='Локатор состояния, в котором сейчас находится чат с пользователем. Заполняется автоматически. Используется стейт-машиной.<br>Пример значения: <code>{"state_class_locator": "/start-menu/"}</code>.<br>В поле хранится объект JSON в формате локатора из библиотеки <a href="https://pypi.org/project/yostate/">yostate</a>: атрибут <code>state_class_locator</code> указывает локатор класса состояния и похож на часть адреса URL, атрибут <code>params</code> задаёт параметры состояния.', null=True, verbose_name='состояние')),
                ('mailing_failure_reason', models.SlugField(blank=True, help_text='Англоязычный код ошибки по результатам рассылки, например "endless_loop". Если поле осталось пустым после рассылки — значит прошло успешно. Разрешены те же символы, что бывают внутри slug.', verbose_name='код ошибки рассылки')),
                ('mailing_failure_debug_details', models.TextField(blank=True, help_text='Описание ошибки по результатам рассылки. Поле хранит отладочную информацию для программиста.', verbose_name='описание ошибки рассылки')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'abstract': False,
                'unique_together': {('tg_user_id', 'funnel_slug')},
            },
        ),
    ]
