Editable messages: !product
  ключевые функции:
    - Контент-менеджер -- Управлять сообщениями бота через админку
      - Через админку выполнять CRUD операции
      - с TextMessage
      - с ImageMessage
      - Через админку получить предуждение об опасном действии с текстовкой
      - Готовить переводы TextMessage на языки поддерживаемые чат-ботом
      - Выгружать из БД одним файлом, а затем загружать их обратно в БД
      - текстовые сообщения
      - сообщения с картинками
      - сообщения с кнопками

    - Контент-менеджер -- Управлять кнопками бота через админку
      - Через админку выполнять CRUD операции с кнопками бота
      - Через админку назначить разные кнопки для разных языков
      - Через админку добавлять кнопки с callback_data, соответствующим маске или регулярному выражению
      - Через админку добавлять кнопки не предусмотренные программистом
      - кнопки-ссылки
      - кнопки-дублёры
      - кнопки-редиректы

    - Контент-менеджер -- спланировать свою работу по отчету о недостающих сообщениях и кнопок

    - Системный администратор -- Поддерживать исправную работу чат-бота
      - Убедиться, что существуют все необходимые для работы бота сообщения и кнопки для указанного языка
      - Получить подробный отчет для контент-менеджера об отсутствии необходимых сообщений и кнопок

    - Разработчик чат-бота -- Разработать бота с возможностью управлять сообщениями и кнопками из веб-интерфейса
      - Перенести сообщения из уже написанного кода в Editable messages
      - Интегрировать приложение Editable messages в код чат-бота на базе Django Tg Bot Framework
      - в триггерные рассылки
      - в разовые рассылки создаваемые через админку
      - в интерфейс бота с менюшками реализованного с помощью стейтов
      - в код без стейтов
      - Управлять набором обязательных кнопок бота

  запрещённые функции:
    - Контент-менеджер --
    - Системный администратор --
    - Разработчик чат-бота --


Контент-менеджер: !role
  Мотивация:
    - Поддерживать актуальность и корректность в сообщениях и кнопках бота.
  Старт: Админ-панель бота.


Системный администратор: !role
  Мотивация:
    - Поддерживать исправную работу бота
  Старт: Страница главного репозитория


Разработчик чат-бота: !role
  Мотивация:
    - Разработать чат-бота с возможностью управления сообщениями и кнопками со стороны КМ.
  Старт: Страница главного репозитория
